# Daily Project Configuration
# This is a managed project where oh-my-dockers manages all services

[project]
name = "daily"
domain = "daily.local"
mode = "managed"  # oh-my-dockers manages services and network
# port_offset = 0  # Optional: Port offset for databases (default: 0)
# If you need to run multiple managed projects, set different offsets:
# - daily: port_offset = 0 (PostgreSQL: 5432, Redis: 6379)
# - test:  port_offset = 100 (PostgreSQL: 5532, Redis: 6479)

[services]
# Database services
postgres = { enabled = true, version = "latest" }
redis = { enabled = true, version = "latest" }
surrealdb = { enabled = true, version = "latest" }

# AI services
chroma = { enabled = true, version = "latest" }
ollama = { enabled = false, version = "latest" }

# Workflow services
n8n = { enabled = true, version = "latest" }

[network]
name = "daily-net"

[caddy]
# Automatically generate subdomains for enabled services
# This will create: postgres.daily.local, redis.daily.local, etc.
auto_subdomains = true

# Additional custom routes (optional)
# routes = [
#     { subdomain = "api", target = "daily-backend:8080" },
#     { subdomain = "app", target = "daily-frontend:3000" }
# ]

