# Example Project Configuration
# This is a proxy-only project where services are managed externally

[project]
name = "example"
domain = "example.local"
mode = "proxy-only"  # Only provide reverse proxy, don't manage services

[network]
name = "example-net"
external = true  # Use externally created network

[caddy]
# Define routes for external services
routes = [
    { domain = "example.local", target = "example-frontend:80" },
    { subdomain = "api", target = "example-backend:3000" },
    { subdomain = "admin", target = "example-admin:8080" },
]

