[package]
name = "hosts"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "hosts"
path = "src/main.rs"

[dependencies]
clap.workspace = true
serde.workspace = true
toml.workspace = true
anyhow.workspace = true
colored.workspace = true

