[package]
name = "cert"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "cert"
path = "src/main.rs"

[dependencies]
clap.workspace = true
anyhow.workspace = true
colored.workspace = true

