-- Create n8n user
CREATE USER n8n WITH PASSWORD 'n8n';

-- Grant connect and usage privileges on daily database
GRANT ALL PRIVILEGES ON DATABASE daily TO n8n;
GRANT CONNECT ON DATABASE daily TO n8n;

-- Connect to daily database
\c daily;

-- Create n8n schema
CREATE SCHEMA IF NOT EXISTS n8n AUTHORIZATION n8n;

-- Grant all privileges on schema
GRANT ALL ON SCHEMA n8n TO n8n;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA n8n TO n8n;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA n8n TO n8n;
ALTER DEFAULT PRIVILEGES IN SCHEMA n8n GRANT ALL ON TABLES TO n8n;
ALTER DEFAULT PRIVILEGES IN SCHEMA n8n GRANT ALL ON SEQUENCES TO n8n;

