services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:${N8N_VERSION:-latest}
    container_name: ${PROJECT_NAME}-n8n
    restart: unless-stopped
    environment:
      - DB_TYPE=${N8N_DB_TYPE:-postgresdb}
      - DB_POSTGRESDB_HOST=${PROJECT_NAME}-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-${PROJECT_NAME}}
      - DB_POSTGRESDB_USER=${N8N_DB_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_PASSWORD:-n8n}
      - DB_POSTGRESDB_SCHEMA=n8n
      - GENERIC_TIMEZONE=${TIMEZONE:-Asia/Tokyo}
      - TZ=${TIMEZONE:-Asia/Tokyo}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - WEBHOOK_URL=https://n8n.${PROJECT_DOMAIN}
    volumes:
      - ${PROJECT_NAME}_n8n_data:/home/node/.n8n
    networks:
      - ${PROJECT_NETWORK}
      - caddy-net
    depends_on:
      - postgres

volumes:
  ${PROJECT_NAME}_n8n_data:

networks:
  ${PROJECT_NETWORK}:
    external: true
  caddy-net:
    external: true

